return {
    COMBAT_CLIENT_REMOTE_EVENT_NAME = "CombatClient";

    EQUIP_REMOTE_FUNCTION_NAME = "Equip";
    USE_WEAPON_REMOTE_FUNCTION_NAME = "UseWeapon";
    ATTACK_REMOTE_FUNCTION_NAME = "Attack";

    DUMMY_ATTACK_REMOTE_EVENT_NAME = "OnDummyHit";

    TARGET_HEALED_REMOTE_EVENT_NAME = "TargetHealed";
    TARGET_DAMAGED_REMOTE_EVENT_NAME = "TargetDamaged";
}