return {
    STAGE_NAMES = {
        "Finding the magic%s";
        "Sending the sorcerers%s";
        "Tuning the vortex%s";
        "Heating up chocolate%s";
        "Chilling hot chocolate%s";
        "Lighting up campfires%s";
        "Hiding the wizards%s";
        "Mixing a brew%s";
        "Feeding a cat%s";
        "Making winters cold%s";
        "Making winters chilly%s";
        "Making summers warm%s";
        "Making summers hot%s";
        "Building a castle%s";
        "Building a sandcastle%s";
        "Flooding the oceans%s";
        "Stirring up storms%s";
        "Sprinkling some flowers%s";
        "Fixing up sticks%s";
        "Picking up branches%s";
        "Dropping some leaves%s";
        "Starting the rain%s";
        "Stopping the rain%s";
        "Starting the snow%s";
        "Stopping the snow%s";
        "Training the dummies%s";
        "Reducing dummy sentience%s";
        "Drying out hay%s";
        "Creating bosses%s";
        "Building a scarecrow%s";
        "Building a snowman%s";
        "Tilling the soil%s";
        "Tending the crops%s";
        "Grinding up wheat%s";
        "Baking some bread%s";
        "Picking some locks%s";
        "Hiding some gold%s";
        "Sharpening swords%s";
        "Hardening hammers%s";
        "Chiseling axes%s";
        "Stitching a quilt%s";
        "Growing the pumpkins%s";
        "Assembling clans%s";
        "Building all houses%s";
        "Painting a picture%s";
        "Distributing treaures%s";
        "Unlocking the dungeons%s";
        "Checking on Malaghar%s";
        "Poking Malaghar%s";
        "Malaghar!";
        "Can't find Malaghar%s";
        "It's not MaLGAhar!";
        "Scattering some hints%s";
        "Simulating battles%s";
        "Winter is here%s";
        "Placing Snowmelt%s";
        "Shaping Wintertusk%s";
        "EPIC PLACEHOLDER!";
    };
}