return {
    CREATE_PARTY_REMOTE_EVENT_NAME = "CreateParty";
    JOIN_PARTY_REMOTE_EVENT_NAME = "JoinParty";
    LEAVE_PARTY_REMOTE_EVENT_NAME = "LeaveParty";
    SEND_INVENTORY_REMOTE_EVENT_NAME = "SendInventory";
    START_PARTY_REMOTE_EVENT_NAME = "StartParty";
    UPDATE_TABLE_REMOTE_EVENT_NAME = "UpdateTable";

    PARTY_EXPIRATION_TIME = 180;
    TEMP_DUNGEONPLACEID = 9678777751;
}