return {
    GET_ITEMS_REMOTE_FUNCTION_NAME = "GetItemsRemoteFunction";
    SET_EQUIPPED_ITEM_REMOTE_FUNCTION_NAME = "SetEquippedItemRemoteFunction";

    SET_SETTING_REMOTE_FUNCTION_NAME = "SetSetting";
    GET_SETTING_REMOTE_FUNCTION_NAME = "GetSetting";
    GET_SETTINGS_REMOTE_FUNCTION_NAME = "GetSettings";

    HAS_BEATEN_DUNGEON_REMOTE_FUNCTION_NAME = "HasBeatenDungeon";
    HAS_PLAYED_DUNGEON_REMOTE_FUNCTION_NAME = "HasPlayedDungeon";
}